Build main page framework - still needs functionality and icons though
CONUN-Global/conun-wallet-webapp pull request #43
Opened 2021-09-09 02:09 UTC by BruceJi7

2021-09-09 02:21 UTC, BruceJi7 commented
I will add some more updated icons, stand by

2021-09-09 02:50 UTC, ivanms1 requested changes

2021-09-09 02:50 UTC, ivanms1 commented on src/pages/Home/MainSection/ActionsSection/index.tsx
> +import TransactionHistory from "./TransactionHistory";
order

2021-09-09 02:50 UTC, ivanms1 commented on src/pages/Home/MainSection/TokenCard/index.tsx
> +            <CopyIcon />
could add functionality to this?

2021-09-09 02:51 UTC, BruceJi7 commented on src/pages/Home/MainSection/TokenCard/index.tsx
> +            <CopyIcon />
To the copy icon? It wil become a button later

2021-09-13 02:41 UTC, ivanms1 approved these changes

2021-09-13 02:53 UTC, merged