Intro css styling
CONUN-Global/conun-wallet-webapp pull request #44
Opened 2021-09-09 02:25 UTC by JM066

2021-09-09 03:05 UTC, ivanms1 requested changes
also check conflicts

2021-09-13 04:23 UTC, BruceJi7 approved these changes

2021-09-13 04:29 UTC, ivanms1 requested changes

2021-09-13 04:29 UTC, ivanms1 commented on src/components/Form/HookForm/FormInput/index.tsx
> +// import inputStyles from "../../Input/Input.module.scss";
remove please

2021-09-13 04:29 UTC, ivanms1 commented on src/components/Header/index.tsx
>    const isSelectBlue = BLUE_SELECT_STEPS.includes(currentStep.current);
add a space to separate from hooks

2021-09-13 04:29 UTC, ivanms1 commented on src/components/Header/index.tsx
> +  }
add space

2021-09-13 04:29 UTC, ivanms1 commented on src/pages/Intro/Backup/ModalConfirmation/ModalConfirmation.module.scss
> +  & .ConfirmContainer {
add space between class names

2021-09-13 04:29 UTC, ivanms1 commented on src/pages/Intro/HelpUs/index.tsx
>    const setIsLoggerActive = useStore((state) => state.setIsLoggerActive);
```suggestion
  const setIsLoggerActive = useStore((store) => store.setIsLoggerActive);
```

2021-09-13 04:29 UTC, ivanms1 commented on src/pages/Intro/ImportWallet/index.tsx
> +      return;
use `else`

2021-09-13 04:29 UTC, ivanms1 commented on src/pages/Intro/WalletQuestion/index.tsx
> +  const currentStep = useStore((state) => state.currentStep);
```suggestion
  const currentStep = useStore((store) => store.currentStep);
```

2021-09-13 05:07 UTC, ivanms1 approved these changes

2021-09-13 05:07 UTC, ivanms1 commented
merge once conflicts are solved @JM066

2021-09-13 05:23 UTC, merged