Login css
CONUN-Global/conun-wallet-webapp pull request #53
Opened 2021-09-15 08:44 UTC by JM066

2021-09-15 12:12 UTC, BruceJi7 commented
This pull request is 32 files, it's shuge 😁

2021-09-15 12:14 UTC, BruceJi7 commented on src/components/UserBox/UserBox.module.scss
> +    border: solid 3px #fff !important;
I assume that !important is the only way to get this to work?
If it's something we have control over, you could also try changing the order the classes are applied

2021-09-15 12:16 UTC, BruceJi7 commented on src/hooks/useLogin.tsx
> +      console.log(getIdentity(), "get identity");
I spy a console log!

2021-09-15 12:20 UTC, BruceJi7 approved these changes
The only thing is there is a stray console.log :D nice

2021-09-16 00:42 UTC, ivanms1 requested changes
just some small changes

2021-09-16 00:42 UTC, ivanms1 commented on src/pages/Intro/PasswordSetup/index.tsx
>                message: "Password must be at least 5 characters long",
change error message too

2021-09-16 00:54 UTC, JM066 commented on src/components/UserBox/UserBox.module.scss
> +    border: solid 3px #fff !important;
The css from google was unoverwritable so I used !important  😁 Initially I made an outer circle but it was not round? enough.

2021-09-16 02:00 UTC, ivanms1 commented
@JM066 remember to resolve the conversations once you solved the issues

2021-09-23 05:22 UTC, BruceJi7 commented on package.json
> +    "react-tooltip": "^4.2.21",
I'll approve it with this in, but we have to experiment with this package, it may work okay and maybe not. Let's see!

2021-09-23 05:34 UTC, BruceJi7 approved these changes

2021-09-23 05:34 UTC, BruceJi7 commented
Haha Ivan approve yo changes man @ivanms1

2021-09-23 05:42 UTC, ivanms1 approved these changes

2021-09-23 05:42 UTC, merged